module.exports.categories = [
  "Agriturismo",
  "Trattoria",
  "Osteria",
  "Ristorante",
  "Pizzeria",
  "Fast Food",
  "Caffetteria",
  "Gelateria",
  "Taverna",
  "Bistrot",
  "Hotel",
  "Bed & Breakfast",
  "Agriturismo",
  "Resort",
  "Camping",
  "Casa vacanze",
  "Residence",
  "Rifugio",
  "Escursione",
  "Passeggiata panoramica",
  "Parco naturale",
  "Bosco",
  "Zoo",
  "Giadino botanico",
  "Cascata",
  "Lago",
  "Grotta",
  "Museo d'arte",
  "Museo storico",
  "Museo archeologico",
  "Museo scientifico",
  "Museo naturalistico",
  "Centro storico",
  "Terrazza",
  "Punto panoramico",
  "Mercato locale",
  "Monumento",
  "Giardino pubblico",
  "Vita notturna",
  "Parco giochi",
  "Fattoria didattica",
  "Museo per bambini",
  "Laboratorio creativo",
  "Teatro",
  "Cinema",
  "Spettacolo",
  "Concerto",
  "Acquario",
  "Parco tematico",
  "Festival",
];

module.exports.names = [
  "Valle Verdi",
  "Bosco Incantato",
  "Fonti Alte",
  "Colle Dorato",
  "Roccia Blu",
  "Piana dei Ciliegi",
  "Vento Lento",
  "Campi Solari",
  "Fiume Quieto",
  "Stella d’Oro",
  "Radura Segreta",
  "Pendii Azzurri",
  "Terre Rosse",
  "Fonte delle Ninfe",
  "Corte delle Lucciole",
  "Poggio delle More",
  "Isola Verde",
  "Rifugio delle Querce",
  "Sentiero Magico",
  "Collina dei Gufi",
  "Cascata Bianca",
  "Prati del Sole",
  "Bosco delle Fate",
  "Vallata Serena",
  "Rocce del Tramonto",
  "Giardino delle Nebbie",
  "Alture Fiorite",
  "Laghetto dei Sogni",
  "Campo delle Stelle",
  "Grotta di Cristallo",
  "Terrazza del Vento",
  "Pianura Dorata",
  "Foresta dei Cervi",
  "Ruscello d’Argento",
  "Monte delle Nuvole",
  "Radura delle Viole",
  "Valle dei Sussurri",
  "Colline di Luce",
  "Fonte dei Desideri",
  "Poggio Incantato",
  "Terre di Luna",
  "Bosco dei Ricordi",
  "Sentiero delle Ombre",
  "Corte dei Petali",
  "Rifugio del Silenzio",
  "Pendii di Lavanda",
  "Giardino Segreto",
  "Roccia delle Aquile",
  "Prato delle Melodie",
  "Fiume di Cristallo",
  "Alture del Tempo",
];

module.exports.types = [
  "Non specificato",
  "Cibo",
  "Dormire",
  "Natura",
  "Museo",
  "Città",
  "Per bambini",
];
